### ISSUE TITLE
No response for live video

### ISSUE THREAD

**Issue by RaymondMouthaan** [brutella/hkcam#11]
First of all, thanks for this great peace of software!

I have flashed raspbian-stretch-lite-2019-04-08-hkcam-v0.0.6-armv6.img and all seemed to work fine for less than a day, but after that Live shows "No Response" as shown below. Still image remains to work.

Rebooting the Raspberry PI zero w fixes the issue, but comes back in within a day.  

![IMG_1410](https://user-images.githubusercontent.com/25717738/58532821-fc7ca880-81e6-11e9-976a-0aa72b2da028.png)

![IMG_1411](https://user-images.githubusercontent.com/25717738/58532895-3d74bd00-81e7-11e9-9548-6e0b56f20f2f.jpg)

**Comment by brutella** [comment]
Could you please paste the content of the log file?
You can find instructions on how to access it in the [wiki](https://github.com/brutella/hkcam/wiki/Common-Issues#log-file).

**Comment by RaymondMouthaan** [comment]
Hi Matthias,

I've attached all the log files from /var/log/hkcam because in current I couldn't find anything suspicious. Hope these files help you.

At this very moment hkcam works fine, since I rebooted the PI zero this morning.

[hkcam.zip](https://github.com/brutella/hkcam/files/3233637/hkcam.zip)

**Comment by brutella** [comment]
Thank for the log files. I think I've found the bug.

Please verify that the fix works by compiling hkcam yourself from the [fix-ip-search](https://github.com/brutella/hkcam/tree/fix-ip-search) branch.

You can do that with the following.

1. Make sure that Git and Go are installed.
2. Clone the project with `git clone https://github.com/brutella/hkcam.git`
3. Fetch all branches with `git fetch --all`
4. Checkout the fix-ip-search branch with `git checkout fix-ip-search`
5. Change directory into the project with `cd hkcam`
6. Build hkcam with `make build`
7. Copy the new binary onto the raspberry pi with `scp build/hkcam-_linux_armhf/usr/bin/hkcam pi@raspberrypi.local:~`
8. SSH into the raspberry pi with `ssh pi@raspberrypi.local` (password raspberry)
9. Stop the currently running daemon with `sudo sv stop hkcam`
10. Override the old binary with the new one `sudo mv ~/hkcam /usr/bin/`
11. Restart hkcam with `sudo sv start hkcam`

**Comment by RaymondMouthaan** [comment]
@brutella, great hope it works .. 

Can I do step 1 - 6 on a MAC ?

**Comment by iMartzen** [comment]
I experience the same problems. I will also try this solution. Fingers crossed.

**Comment by iMartzen** [comment]
I worked for me! I am now able to stream LIVE.

**Comment by RaymondMouthaan** [comment]
Like @iMartzen, I followed the steps and hkcam seems to work, lets wait a couple of days to see if it remains to work 👍

**Comment by brutella** [comment]
Thanks all. 
I will release a new image tomorrow when this fixes the issue.

**Comment by RaymondMouthaan** [comment]
@brutella, thank you for fixing it so quickly!

I'll keep you updated if tomorrow still runs fine and then you will see an order for enclosures as well! 😇

**Comment by baseship** [comment]
Back from Nightwork now... followed the steps below - now the stream works!

**Comment by iMartzen** [comment]
My watch cannot receive a LIVE video.  It stays in "Connecting" modi. 
Does anyone experience this too?

![PHOTO-2019-05-30-12-55-50](https://user-images.githubusercontent.com/23737561/58628576-5ca04700-82da-11e9-8146-f6e0ce1ad848.jpg)

**Comment by RaymondMouthaan** [comment]
@brutella, unfortunately same problem re-occurs.

**Comment by brutella** [comment]
[hkcam v0.0.7](https://github.com/brutella/hkcam/releases/tag/v0.0.7) should resolve this issue.

**Comment by RaymondMouthaan** [comment]
@brutella if 0.0.7 is the same as branch fix-ip-search from yesterday, I am afraid the issue remains ...

**Comment by brutella** [comment]
This issue is further discussed in #15

**Comment by RaymondMouthaan** [comment]
> @brutella, thank you for fixing it so quickly!
> 
> I'll keep you updated if tomorrow still runs fine and then you will see an order for enclosures as well! 😇

@brutella, just curious, did you receive my order?

**Comment by iMartzen** [comment]
I agree; thank you for fixing so quickly!
